### ISSUE TITLE
odoo 企业版 破解 | Mixoo

### ISSUE THREAD

**Issue by jellyfrank** [jellyfrank/gitalk#23]
http://mixoo.cn/2018/03/16/odoo-enterprise-hack/ 

 本文仅供参考学习使用，如有需求请订购odoo官方订阅 数据库限制odoo的数据库有使用期限，修改的方法如下： 打开开发者模式，在技术-系统参数中找到 database.expiration_date 修改数据库到期日期。 最新方法上面的方法实际使用中发现会被odoo自动改回来，因为odoo会定期与官方服务器进行通信，把你数据库当前的创建日期和一些使用信息发送回官方，所以，我们需要切断与官方的联系。

**Comment by leangjia** [comment]
学习了，谢谢分享
